import turtle
wn = turtle.Screen()
t1= turtle.Turtle()
size = 100
def f(size) :
	t1.fd(size)
	t1.right(90)
	t1.fd(size)

	
turn = 45
oldps =t1.pos()
oldhead = t1.heading()
oldpos = t1.pos()
t1.setpos(oldpos)
t1.setheading(oldhead+turn)
t1.pendown()
f(size)
t1.home()
t1.clear()
turn= 45
size = 100
oldpos = t1.pos()
oldhead =t1.heading()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead)
t1.pendown()
t1.setheading(oldhead+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+turn)
t1.setheading(oldhead+turn)
t1.setheading(oldhead+turn+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+turn)
t1.setheading(turn)
t1.setheading(oldhead+turn+turn+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+180)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(turn)
t1.setheading(turn+turn+turn+turn+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(270)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(315)
t1.pendown()
f(size)