import turtle
wn = turtle.Screen()
t1 = turtle.Turtle()
size = 100
def f(size) :
	t1.fd(size)
	t1.right(90)
	t1.fd(size)
turn = 22.5
oldpos = t1.pos()
oldhead = t1.heading()
t1.setpos(oldpos)
t1.setheading(oldhead+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+turn+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+turn+turn+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+turn+turn+turn+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+turn+turn+turn+turn+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+turn+turn+turn+turn+turn+turn)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+157.5)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+180)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+202.5)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+225)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+247.5)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+270)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+292.5)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+315)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+337.5)
t1.pendown()
f(size)
t1.penup()
t1.setpos(oldpos)
t1.setheading(oldhead+360)
t1.pendown()
f(size)


